apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-cms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-cms
  template:
    metadata:
      namespace: default
      labels:
        app: check-cms
    spec:
      containers:
        - name: check-cms
          image: pashk88/check-cms
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 600Mi