apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: check-cms
  labels:
    app:  check-cms
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app:  check-cms