version: "3.6"

services:
  consul_server:
    build:
      context: consul_server
      dockerfile: Dockerfile
    image: consul_server
    ports:
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8400:8400
      - 8500:8500
    environment:
      - NODE=consul_server
      - PRIVATE_IP_ADDRESS=10.10.0.2
    networks:
      consul_network:
        ipv4_address: 10.10.0.2
  load_balancer:
    image: fabiolb/fabio
    ports:
      - 9998:9998
      - 9999:9999
    command: -registry.consul.addr="10.10.0.2:8500"
    networks:
      consul_network:
        ipv4_address: 10.10.0.100
  cms_sign_1:
    build:
      context: cms-sign
      dockerfile: Dockerfile
    image: cms_sign_consul
    ports:
      - 8081:8080
    environment:
      - NODE=cms_sign_1
      - LOAD_BALANCER=10.10.0.100
      - PRIVATE_IP_ADDRESS=10.10.0.11
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul_server
      - load_balancer
    cap_add:
      - NET_ADMIN
    networks:
      consul_network:
        ipv4_address: 10.10.0.11
  cms_sign_2:
    build:
      context: cms-sign
      dockerfile: Dockerfile
    image: cms_sign_consul
    ports:
      - 8082:8080
    environment:
      - NODE=cms_sign_2
      - LOAD_BALANCER=10.10.0.100
      - PRIVATE_IP_ADDRESS=10.10.0.12
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - consul_server
      - load_balancer
    cap_add:
      - NET_ADMIN
    networks:
      consul_network:
        ipv4_address: 10.10.0.12

networks:
  consul_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16